# Generated by Django 4.2.1 on 2023-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ortopedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
